// q
// https://github.com/type-challenges/type-challenges/blob/main/questions/00108-medium-trim/README.ja.md

// a
// https://www.typescriptlang.org/play?ssl=21&ssc=122&pln=21&pc=1#code/PQKgUABBCMAMAcEC0EAqAnAlgW0spBheARgJ4QCCAdgC4AWA9leQGICuEAFAAICGtAMzYBKCAGJAtHKAsX3E0AptgAOAG17ykyzPPS9lYPGMMRAVzGB5VX1RA4aaB1bUDoSoCSGQOvKgRQZAa8qAohkCADIEI5QPdegOwZALy9AXzd7QCklQBM0wHUGQH0GQAbTKMARBhsHQBX4wE0GCAADDBwAHlQAPiyIe0B87UBRiKjAPwZ0wCAGCwhAaPlACQZABwZGrK6aAGc8GlJFOQgaLGw5ABMIAF40MbyAcigACTllZQYIAHUGdGUpiAXCiGBgCDkADyGAY3kpmk3iYYXV9c2dvYmFvC6sxuOAOJaZZsYiAcwZAF0egFio9KAaIZAFj-dBoNEUPQAXKdetc6AA6ABWPRxuwA5sA4PBgHjeGAQMB9KAIAB9Zks1ksiCAZQYOYBrBkAzQyAH4ZAJMM9kAGFGAU0UmWypYyILT9AMhnN8gBlc4XeRUCY9CA9UaYKjE46zVWXDVa7IAEgA3gAiCB2gA+9oAOlRHS6aDaAL7W-UCOToCAAJS9JSdWV9VH9gZD1rt7ptroTzs9oYgAH4ldg8kHjmiIMr6SBJdLWRBAGMMgE6GQATDIBGhn5lZLpeZsrpOEUuxoI0GwytEAAogBHNi6AA0A6ucluEC9EAE6AY2EO3AVciQ2N0yjkBrkPWAbBomGUPW+YFXEGuvB6u5mEAA2nh+5PbnkhyPlAV5gtdegjuPv6MRyFKOj7PjQr7Dron75EsP5-occGFMBoE3OBb5Qbk2ZLFAUCIf+iHIVAT6oRB77QVhP44fBAG-khIFEWBpEYV+OG4aMrGHMBCGAXRKFTmhkEfphiw4a6KZzgwjy8IGKbUQIkkQMQ0lAfRE4kehQlftRKl8S+GnkSJYldtpvEALpFk2zYQIAhNb+JW5aAMMMgDrDJZpatmAoB4McgDHkYAKt72IAjoqAJDmcKIsiqIYsAWK4gSRLoKS5LAPwPQAO4BpS1JQD5-mANGRCJIii6KYj02L4oSJJkggwA9AwygHpgTB9FlECALoM-iAGty-iAE1RgAyGWFhWRdFZVxaSVI0nSQA
type Trim<S extends string> = S extends
  | `${" " | "\n" | "\t"}${infer R}`
  | `${infer R}${" " | "\n" | "\t"}`
  ? Trim<R>
  : S;
