// q
// https://github.com/type-challenges/type-challenges/blob/main/questions/00459-medium-flatten/README.ja.md

// a
// https://www.typescriptlang.org/play?#code/PQKgUABBAsCsCcEC0EBiAbAhgF2wUwDtJklSziAjATwgC8ALAewFcqBLAWzYIHMIAKAAIBjehQBOjAJQQAxIFo5QFi+czOPGYqYYrJ0RAVzGB5VS1RAygyA7BkBNUYBkMwOYMgewZAgAyB15UCKDIDXlQMYMgfQZAsomB0JUAkhkBVhkBLhkBhhkAJhkA0ZUB1Bi9AaPUAwC-FQGylQE0GQGiGRMAPs0B5BkBR-UBAyMAZBkAhBkAohkA-BjTAIAZjCEBo+UAJBkAHBgAueoADbuwAZ2JsKgAHPAgAMyxcQggAXjRJ-AIAHgBtAEYAGggAJi2VgGYt6ABdPZWV2GOrgD4IYGAIda3diEOYLcvibs7624BxNjYAASzAoNkAXR6AWKjMoAsf-ouCGvTa9z6ogAdAArXpoxjiHjAODwYAYzBgEDALSgCAAfVpdPpdIgJhMgGsGQDNDIAfhkAkwwBQAYUYBTRRpDOF1Ig5K0gxG8xwiyWAGUIHgAB6LAAmvQgmAIVBWpwgABVFSrCOrNdrdbNHsdbnMIArlWqNStuGM8OIIAANLZon0ut0QACaxwgAH4IMQPUbHWadcGQ8RpVNlisfWivRBU0Gtvrbm1E7KUz6s49U-qth7reGoHn9ZSQEKRfSIIAxhkAnQwRQCNDBzWw3G7SxRTOENcdgIJLRgBvCAAUQAjsxMOgttOlSNhKOAL7jSQcCAAckE46QokX6EIPDwvWAzGwbHQvT3EuGo2EmF6l8tK2IK7X2CWc4XdAlgwGVCFWa09mta4Nm-Vc8HXf950XYCFjAp4di2N4Tmgx5Ngw14jigmCoB-eC-wA5CQKTVY8JWbYbj2PD6OuaDYN-RDAJQ0DkyYvYsL1c4LiuBjcOeTCjg+Ii2LIjjKNQ5MpzGRhGDzPcKFUPdnjzNYAAYIA3LY9yUxh1PEPcIMeRTlNU0zNJ2bS9IM-djNsqTjkpB5D16JBlV-Hy1FxMBx0VAL3TmKjZT3NY92uOtez7CBAEJrMxW2bMJAHWGeLGwHMBQGIW5AGPIwAVbwCQBHRUASHNYXhbBEWRYBUXoTFsVxfFCWALVegAdzdYlSSgQqSsAaMiMjhBEkRRXp0SxHE8QJBBgF6Rh0BvNhGAIfp+ogQBdBjMQA1uUsKxRpq8b6smxrppa3qyQpIA

// other a
type Flatten<S extends any[], T extends any[] = []> = S extends [
  infer X,
  ...infer Y
]
  ? X extends any[]
    ? Flatten<[...X, ...Y], T>
    : Flatten<[...Y], [...T, X]>
  : T;
